params:
  - params.yaml
  - src/params.json
vars:
  - params.yaml
stages:
  htmlretrieve:
    foreach: ${pages} # From params.yaml
    do:
      frozen: true
      cmd: npm start -- html retrieve -u ${item.url}
      params:
        - params.yaml:
          - pages
        - src/params.json:
          - htmlretrieve
          - puppeteer
      deps:
        - src/html/retrieve.ts
      outs:
        - data/${item.path}/index.html
        - data/${item.path}/index.json
      metrics:
        - data/${item.path}/htmlretrieve-metrics.json
  htmlcompress:
    foreach: ${pages} # From params.yaml
    do:
      cmd: npm start -- html compress -u ${item.url}
      params:
        - src/params.json:
          - htmlcompress
      deps:
        - src/html/compress.ts
        - data/${item.path}/index.html
      outs:
        - data/${item.path}/index.compressed.html
      metrics:
        - data/${item.path}/htmlcompress-metrics.json  
  formcode:
    foreach: ${pages} # From params.yaml
    do:
      cmd: npm start -- form code -u ${item.url}
      deps:
        - src/forms/code.ts
        - src/gpt.ts
        - src/lint.ts
        - data/${item.path}/index.compressed.html
      params:
        - src/params.json:
          - formcode
      outs:
        - data/${item.path}/formcode.js
        - data/${item.path}/formcode-lint.json
        - data/${item.path}/formcode-result.json
      metrics:
        - data/${item.path}/formcode-metrics.json  
  formprops:
    foreach: ${pages} # From params.yaml
    do:
      cmd: npm start -- form props -u ${item.url}
      deps:
        - src/forms/props.ts
        - src/gpt.ts
        - data/${item.path}/index.json
        - data/${item.path}/formcode.js
      params:
        - src/params.json:
          - formprops
      outs:
        - data/${item.path}/formprops.json
        - data/${item.path}/formprops-result.json
      metrics:
        - data/${item.path}/formprops-metrics.json  
  formschema:
    foreach: ${pages} # From params.yaml
    do:
      cmd: npm start -- form schema -u ${item.url}
      deps:
        - src/forms/schema.ts
        - src/json
        - src/lint.ts
        - data/${item.path}/formprops.json
      params:
        - src/params.json:
          - formschema
      outs:
        - data/${item.path}/formschema.js
        - data/${item.path}/formschema-lint.json
        - data/${item.path}/formschema-result.json
      metrics:
        - data/${item.path}/formschema-metrics.json
  formfill:
    foreach: ${pages} # From params.yaml
    do:
      cmd: npm start -- form fill -u ${item.url}
      deps:
        - src/puppeteer
        - data/${item.path}/index.json
        - data/${item.path}/formcode.js
        - data/${item.path}/formprops.json
      params:
        - src/params.json:
          - formfill
          - puppeteer
      outs:
        - data/${item.path}/formfill-result.json
      metrics:
        - data/${item.path}/formfill-metrics.json