params:
  - params.json
vars:
  - url: http://localhost/alpha
  - path: localhost/alpha
stages:
  htmlretrieve:
    cmd: npm start -- html retrieve -u ${url}
    params:
      - params.json:
        - htmlretrieve
    deps:
      - src
    outs:
      - data/${path}/index.html
      - data/${path}/index.json
    metrics:
      - data/${path}/htmlretrieve-metrics.json
    frozen: true
  htmlcompress:
    cmd: npm start -- html compress -u ${url}
    params:
      - params.json:
        - htmlcompress
    deps:
      - src
      - data/${path}/index.html
    outs:
      - data/${path}/index.compressed.html
    metrics:
      - data/${path}/htmlcompress-metrics.json  
  formcode:
    cmd: npm start -- form code -u ${url}
    deps:
      - src
      - data/${path}/index.compressed.html
    params:
      - params.json:
        - formcode
    outs:
      - data/${path}/formcode.js
      - data/${path}/formcode-lint.json
      - data/${path}/formcode-result.json
    metrics:
      - data/${path}/formcode-metrics.json  
  formprops:
    cmd: npm start -- form props -u ${url}
    deps:
      - src
      - data/${path}/index.json
      - data/${path}/formcode.js
    params:
      - params.json:
        - formprops
    outs:
      - data/${path}/formprops.json
      - data/${path}/formprops-result.json
    metrics:
      - data/${path}/formprops-metrics.json  
  formschema:
    cmd: npm start -- form schema -u ${url}
    deps:
      - src
      - data/${path}/formprops.json
    params:
      - params.json:
        - formschema
    outs:
      - data/${path}/formschema.js
      - data/${path}/formschema-lint.json
    metrics:
      - data/${path}/formschema-metrics.json
  formfill:
    cmd: npm start -- form fill -u ${url}
    deps:
      - src
      - data/${path}/index.json
      - data/${path}/formcode.js
      - data/${path}/formprops.json
    params:
      - params.json:
        - formfill
    outs:
      - data/${path}/formfill-result.json
    metrics:
      - data/${path}/formfill-metrics.json